###  request to create new Patient modle
POST localhost:4000/patients
Content-Type: application/json

{
  "name": "Ahmad dido2",
  "email": "Test.Tes@Test.com",
  "address": "123 duse streets HBF",
  "dateOfBirth": "1966-11-02",
  "registeredDate": "2025-12-15"
}

###