### Update an existing patient entity
PUT localhost:4000/patients/123e4567-e89b-12d3-a456-426614174000
Content-Type: application/json

{
  "name": "John Doe UPDATED12",
  "email": "doeTest2@Test.com",
  "address": "123dsss St, spa9onm",
  "dateOfBirth": "1985-06-13"
}

###